Tests refactor all in one
Ifkeybirf/php-cource-hexlet pull request #29
Opened 2022-01-28 04:55 UTC by Ifkeybirf

2022-02-04 05:04 UTC, ova777 requested changes

2022-02-04 05:04 UTC, ovaunit commented on src/ex2/Power3.php
> +        return ($a === $b && $a = 1);
Зачем у тебя в условии `$a = 1` - это присвоение числа переменной $a - эта часть всегда будет true. Мне кажется это лишнее.

2022-02-04 05:04 UTC, ovaunit commented on src/ex3/Fibonachi.php
> +    public function fib(int $n)
return type

2022-02-04 05:04 UTC, ovaunit commented on src/ex3/Fibonachi.php
> +        $myFibObj = new \PHPCourse\ex3\Fibonachi();
Вместо создания нового экземпляра класса достаточно использовать `$this`

2022-02-04 05:04 UTC, ovaunit commented on src/ex4/AddDigits.php
> +            case ($userInput >= 0 && $userInput < 10):
`$userInput >= 0` - излишнее, т.к. если бы значение было меньше нулz - мы бы попали в предыдущий case

2022-02-04 05:04 UTC, ovaunit commented on src/ex4/AddDigits.php
> +                    return (new \PHPCourse\ex4\AddDigits())->addDigits($res);
Вместо создания нового экземпляра класса достаточно использовать `$this`

2022-02-04 05:04 UTC, ovaunit commented on src/ex8/FizzBuzz.php
> +    public function fizzBuzz(int $begin, int $end): string
По условию задачи метод должен печатать на экран, а не возвращать значение

2022-02-04 05:04 UTC, ovaunit commented on src/ex8/FizzBuzz.php
> +            $resFizz = FizzBuzz::isDivision($qq, 3);
Метод isDivision не статичесткий, поэтому вызывать его нужно через $this

2022-02-04 05:04 UTC, ovaunit commented on tests/ex1/BinarySumTest.php
> +namespace PHPCource\ex1;
В тестах должен быть свой неймспейс. Например `PHPCourse\Tests\...`
Нужно поправить у всех тестов.

2022-02-04 05:04 UTC, ovaunit commented on tests/ex2/Power3Test.php
> +        self::assertEquals((int)$check->isPowerOfThree($digit), $expected);
Не нужно результат приводить к int, просто нужно сравнивать с bool

2022-02-04 05:04 UTC, ovaunit commented on tests/ex2/Power3Test.php
> +    public function testPower3($digit, $expected): void
Типы аргументов должны быть указаны во всем твоем коде, и в тестах тоже. Пожалуйста поправь у всех тестов.
`public function testPower3(int $digit, bool $expected): void`

2022-02-04 05:04 UTC, ovaunit commented on tests/ex3/FibonachiTest.php
> +     * @return       void
Не нужно писать return type в аннотации, в заголовке метода это уже есть.

2022-02-04 05:04 UTC, ovaunit commented on tests/ex3/FibonachiTest.php
> +
лишняя строка

2022-02-04 05:04 UTC, ovaunit commented on tests/ex3/FibonachiTest.php
> +        return [
Метод fib, который ты тестируешь принимает int, соответственно тут все значения должны быть int а не string

2022-02-04 05:04 UTC, ovaunit commented on tests/ex4/AddDigitsTest.php
> +     * @return       void
Это лишнее - type уже есть в заголовке функции

2022-02-04 05:04 UTC, ovaunit commented on tests/ex4/AddDigitsTest.php
> +
лишняя строка

2022-02-04 05:04 UTC, ovaunit commented on tests/ex4/AddDigitsTest.php
> +        return [
Все значения должны быть int, как указано в аргументах метода AddDigits::addDigits

2022-02-04 05:04 UTC, ovaunit commented on tests/ex5/BracketsTest.php
> +        //self::assertEquals((int)$check->isBalanced($input), $expected);
Не должно быть лишнего закомментированного кода, в котором нет смысла. Нужно избавляться от него в ПР

2022-02-04 05:04 UTC, ovaunit commented on tests/ex5/BracketsTest.php
> +        self::assertEquals((int)(new Brackets())->isBalanced($input), $expected);
Не нужно результат приводить к int, просто нужно сравнивать результат с bool

2022-02-04 05:04 UTC, ovaunit commented on tests/ex5/BracketsTest.php
> +            ['(()())(())())', '0'],
второе значение должно быть bool

2022-02-04 05:04 UTC, ova777 commented on tests/ex5/BracketsTest.php
> +     * @return       void
Это лишнее - return type уже есть в заголовке функции

2022-02-04 05:04 UTC, ova777 commented on tests/ex6/PerfectTest.php
> +     * @return       void
Это лишнее - return type уже есть в заголовке функции

2022-02-04 05:04 UTC, ova777 commented on tests/ex6/PerfectTest.php
> +        self::assertEquals((int)$checker->isPerfect($control), $expect);
Не нужно результат приводит к int, просто нужно сравнивать с bool

2022-02-04 05:04 UTC, ova777 commented on tests/ex7/HappyTicketTest.php
> +
лишняя строка

2022-02-04 05:04 UTC, ova777 commented on tests/ex7/HappyTicketTest.php
> +        $real = (int)$check->isHappy($num);
Не нужно преобразовывать результат, просто нужно сравнивать его с bool а не с int

2022-02-04 05:04 UTC, ova777 commented on tests/ex7/HappyTicketTest.php
> +     * @expectedException \InvalidArgumentException
deprecated аннотация - удалить

2022-02-04 05:04 UTC, ova777 commented on tests/ex7/HappyTicketTest.php
> +     * @return            array
Во-первых метод ничего не возвращает, во-вторых вместо аннотации нужно указать return type в заголовке метода

2022-02-04 05:04 UTC, ova777 commented on tests/ex8/FizzBuzzTest.php
> +     * return        void
Это лишнее - return type уже есть в заголовке функции

2022-02-04 05:04 UTC, ova777 commented on tests/ex8/FizzBuzzTest.php
> +
лишняя строка

2022-02-04 05:04 UTC, ova777 commented on composer.json
>          "test": "phpunit ",
лишний пробел после phpunit

2022-02-04 05:04 UTC, ova777 commented on composer.json
лишний перевод строки

2022-02-04 05:17 UTC, Ifkeybirf commented on src/ex2/Power3.php
> +        return ($a === $b && $a = 1);
это сравнение с 1 должно было быть. поправил

2022-02-04 05:19 UTC, Ifkeybirf commented on src/ex3/Fibonachi.php
> +    public function fib(int $n)
fixed

2022-02-04 05:22 UTC, Ifkeybirf commented on src/ex3/Fibonachi.php
> +        $myFibObj = new \PHPCourse\ex3\Fibonachi();
fixed

2022-02-04 05:29 UTC, Ifkeybirf commented on src/ex4/AddDigits.php
> +            case ($userInput >= 0 && $userInput < 10):
fixed

2022-02-04 05:29 UTC, Ifkeybirf commented on src/ex4/AddDigits.php
> +                    return (new \PHPCourse\ex4\AddDigits())->addDigits($res);
fixed

2022-02-04 05:29 UTC, Ifkeybirf commented on src/ex8/FizzBuzz.php
> +            $resFizz = FizzBuzz::isDivision($qq, 3);
fixed

2022-02-04 05:29 UTC, Ifkeybirf commented on src/ex8/FizzBuzz.php
> +    public function fizzBuzz(int $begin, int $end): string
напечатать могу. но тогда пока не знаю как покрывать тестами, буду думать..

2022-02-04 07:15 UTC, Ifkeybirf commented on src/ex8/FizzBuzz.php
> +    public function fizzBuzz(int $begin, int $end): string
fixed

2022-02-04 08:35 UTC, Ifkeybirf commented on tests/ex1/BinarySumTest.php
> +namespace PHPCource\ex1;
changed to PHPCourseTest\..

2022-02-04 08:37 UTC, Ifkeybirf commented on tests/ex2/Power3Test.php
> +        self::assertEquals((int)$check->isPowerOfThree($digit), $expected);
fixed

2022-02-04 08:54 UTC, Ifkeybirf commented on tests/ex2/Power3Test.php
> +    public function testPower3($digit, $expected): void
fixed (but not sure about getInstance() in singleton)

2022-02-04 09:31 UTC, Ifkeybirf commented on tests/ex3/FibonachiTest.php
> +     * @return       void
fixed

2022-02-04 09:31 UTC, Ifkeybirf commented on tests/ex3/FibonachiTest.php
> +
fixed.
странно что линтер не сругнулся..

2022-02-04 09:32 UTC, Ifkeybirf commented on tests/ex3/FibonachiTest.php
> +        return [
поправил, кажется.

2022-02-04 09:32 UTC, Ifkeybirf commented on tests/ex4/AddDigitsTest.php
> +     * @return       void
fixed

2022-02-04 09:33 UTC, Ifkeybirf commented on tests/ex4/AddDigitsTest.php
> +
fixed.
опять же, странно что линтер не сругнулся

2022-02-04 09:33 UTC, Ifkeybirf commented on tests/ex4/AddDigitsTest.php
> +        return [
поправил

2022-02-04 09:34 UTC, Ifkeybirf commented on tests/ex5/BracketsTest.php
> +        //self::assertEquals((int)$check->isBalanced($input), $expected);
пщчистил

2022-02-04 09:35 UTC, Ifkeybirf commented on tests/ex5/BracketsTest.php
> +        self::assertEquals((int)(new Brackets())->isBalanced($input), $expected);
fixed

2022-02-04 09:35 UTC, Ifkeybirf commented on tests/ex5/BracketsTest.php
> +            ['(()())(())())', '0'],
fixed

2022-02-04 09:35 UTC, Ifkeybirf commented on tests/ex6/PerfectTest.php
> +     * @return       void
fixed

2022-02-04 09:35 UTC, Ifkeybirf commented on tests/ex6/PerfectTest.php
> +        self::assertEquals((int)$checker->isPerfect($control), $expect);
fixed

2022-02-04 09:36 UTC, Ifkeybirf commented on tests/ex7/HappyTicketTest.php
> +
fixed

2022-02-04 09:36 UTC, Ifkeybirf commented on tests/ex7/HappyTicketTest.php
> +        $real = (int)$check->isHappy($num);
fixed
actually in all tests in this PR

2022-02-04 09:39 UTC, Ifkeybirf commented on tests/ex7/HappyTicketTest.php
> +     * @return            array
вроде поправил

2022-02-04 09:39 UTC, Ifkeybirf commented on tests/ex7/HappyTicketTest.php
> +     * @expectedException \InvalidArgumentException
done

2022-02-04 09:41 UTC, Ifkeybirf commented on tests/ex8/FizzBuzzTest.php
> +     * return        void
fixed

2022-02-04 09:41 UTC, Ifkeybirf commented on tests/ex8/FizzBuzzTest.php
> +
fixed

2022-02-08 13:37 UTC, ova777 requested changes
1. Синглтоны правильно реализовал, но немного кодстайл подправить нужно (см. комментарии).
2. В composer.json я оставлял пару комментариев - поправь их тоже.
3. Загляни еще в phpunit.xml.dist - там ты забыл copyright Plesk'овский
В остальном уже почти отлично!

2022-02-08 13:37 UTC, ova777 commented on src/ex3/Fibonachi.php
> +            return 'invalid input value';
Не должен метод возвращать string, вместо этого должно быть исключение

2022-02-08 13:37 UTC, ova777 commented on src/ex4/AddDigits.php
> +    protected static $_instance;
Не нужно переменные (и методы) называть начиная с "_" - так делали раньше, когда не было модификаторов доступа.
Кстати, на это у тебя ругается линтер. В HappyTicket аналогично.

2022-02-08 13:37 UTC, ova777 commented on src/ex4/AddDigits.php
> +            self::$_instance = new self;
При создании инстанса всегда нужно писать скобки: `new self();`
На это у тебя ругается линтер. В HappyTicket аналогично.

2022-02-08 13:37 UTC, ova777 commented on src/ex4/AddDigits.php
> +    public function addDigits(int $userInput)
return type

2022-02-08 13:37 UTC, ova777 commented on src/ex7/HappyTicket.php
> +use function PHPUnit\Framework\throwException;
Эта функция в классе не используется - лишний use

2022-02-08 13:37 UTC, ova777 commented on src/ex7/HappyTicket.php
> +    private function __construct()
Не хватает перевода строки выше

2022-02-08 13:37 UTC, ova777 commented on src/ex7/happyTicket_v1_1.php
>  <?php
Зачем этот файл тут? Для работы с HappyTicket у тебя теперь есть тесты.
Нужно или разместить его в src (и воспользоваться нормальным автолоадингом для HappyTicket), или лучше удалить его.

2022-02-08 13:37 UTC, ova777 commented on src/ex8/FizzBuzz.php
> +            $resFizzBuzz = ($resFizz && $resBuzz);
Эта переменная не используется

2022-02-08 13:37 UTC, ova777 commented on tests/ex1/BinarySumTest.php
> +namespace ex1;
Ты же писал что сделал namespace PHPCourseTest. Так было бы правильнее, что бы все тесты были под одним общим неймспейсом - PHPCourseTest\exN. Относится и к остальным тестам.

2022-02-08 13:37 UTC, ova777 commented on tests/ex2/Power3Test.php
> +        self::assertEquals($check->isPowerOfThree($digit), $expected);
isPowerOfThree возвращает bool, а ты сравниваешь с int

2022-02-08 13:37 UTC, ova777 commented on tests/ex7/HappyTicketTest.php
> +        $real = $check->isHappy($num);
Обычно называют не real, а actual

2022-02-08 13:37 UTC, ova777 commented on tests/ex7/HappyTicketTest.php
> +     * @dataProvider      happyTicketWrongProvider
Зачем тут 4 лишних пробела перед happyTicketWrongProvider?

2022-02-08 13:37 UTC, ova777 commented on tests/ex8/FizzBuzzTest.php
> +        self::assertStringMatchesFormat((new \PHPCourse\ex8\FizzBuzz())->fizzBuzzCalc($begin, $end), $exp);
Метод assertStringMatchesFormat сравнивает строку с форматом (как в sprintf например), у тебя же просто сравнение строк - подошел бы просто assertEquals

2022-02-08 13:37 UTC, ova777 commented on tests/ex8/FizzBuzzTest.php
> +            ];
Лишние 4 пробела

2022-02-08 13:37 UTC, ova777 commented on src/ex7/HappyTicket.php
> +    public function randomTicketNumber(int $cnt): string
Не хватает перевода строки выше

2022-02-08 13:37 UTC, ova777 commented on tests/ex8/FizzBuzzTest.php
> +            [11, 13, '11 Fizz 13 '],
У тебя fizzBuzzCalc работает не совсем корректно - оставляет на конце лишний пробел, и ты под это подогнал тесты, что есть неправильно. Нужно переделать fizzBuzzCalc что бы на конце не было пробела (и поправить тест).
И добавить кейс когда он возвращает пустую строку (begin > end).

2022-02-08 13:37 UTC, ova777 commented on tests/ex6/PerfectTest.php
> +        self::assertEquals($checker->isPerfect($control), $expect);
expected должен быть первым аргументом - это влияет на вывод в случае если тест провалится.
В testFibonachi аналогично.

2022-02-09 02:41 UTC, Ifkeybirf commented on tests/ex1/BinarySumTest.php
> +namespace ex1;
тогда ругается
Namespace name doesn't match the PSR-0/PSR-4 project structure 
и предлагает мувнуть тесты в tests/PHPCourseTests/ex*

вернул неймспейс PHPCourseTest\ex*

2022-02-09 04:49 UTC, ova777 requested changes

2022-02-09 04:49 UTC, ova777 commented on src/ex3/Fibonachi.php
> +            throw new \InvalidArgumentException('input digit must be >= 0');
исключение ты добавил, а тестом не покрыл

2022-02-09 04:49 UTC, ova777 commented on tests/PHPCourseTest/ex2/Power3Test.php
> +        self::assertEquals($check->isPowerOfThree($digit), $expected);
expected должен быть первым аргументом

2022-02-09 04:49 UTC, ova777 commented on tests/PHPCourseTest/ex8/FizzBuzzTest.php
> +            ['', 13, 11]
Не хватает запятой в конце

2022-02-09 04:49 UTC, ova777 commented on src/ex8/run.php
> +<?php
Опять лишний файл остался

2022-02-09 04:49 UTC, ova777 commented on tests/PHPCourseTest/ex7/HappyTicketTest.php
> +            ['2a']
Не хватает запятой в конце

2022-02-09 05:50 UTC, merged