solution for excersice#4: add digits
Ifkeybirf/php-cource-hexlet pull request #6
Opened 2021-12-18 17:12 UTC by Ifkeybirf

2021-12-24 10:27 UTC, ova777 requested changes

2021-12-24 10:27 UTC, ova777 commented on practice/add_digits/addDigits.php
> +        {
В кейсах не нужно код обрамлять в фигурные скобки

2021-12-24 10:27 UTC, ova777 commented on practice/add_digits/addDigits.php
> +            (string) $str = '' . $userInput;
Если есть желание привести userInput к string, надо писать так:
`$str = (string)userInput;`
И между (string) и переменной не должно быть пробела.

2021-12-24 10:27 UTC, ova777 commented on practice/add_digits/addDigits.php
> +                return $res;
Этот блок нужно взять в фигурные скобки

2021-12-24 10:27 UTC, ova777 commented on practice/add_digits/addDigits.php
> +                $res += (int) $str[$qq];
Когда приводим типы, между `(int)` и `$str` не должно быть пробела

2021-12-24 10:27 UTC, ova777 commented on practice/add_digits/addDigits.php
> +    switch ($userInput) {
switch-case работает следующим образом, допустим есть код:
```
switch($foo) {
    case $bar:
        return 1;
    case $baz:
        return 2;
    // other cases
}
```
сначала $foo сравнивается с $bar, если они равны - попадаем в первый кейс.
если нет, сравниваем $foo с $baz - если совпадают - попадаем во второй кейс.
если нет - идем дальше.
В твое коде, получается, ты делаешь следующие сравнения:
1. $userInput == $userInput < 0
2. $userInput == $userInput < 10
и т.д.
Мне кажется ты хотел написать `switch(true) {`

2021-12-28 03:11 UTC, ova777 requested changes
Всё отлично, нужно всего пару мелких доработок.

2021-12-28 03:11 UTC, ova777 commented on practice/add_digits/addDigits.php
> +        return $res;
Этот return относится к случаю `($userInput > 9)`, соответственно у него должен быть такой же отступ как остального кода в этом case

2021-12-28 03:11 UTC, ova777 commented on practice/add_digits/addDigits.php
> +    return $res;
Этот return не нужен, т.к. мы никогда до него не дойдем.

2021-12-28 04:00 UTC, Ifkeybirf commented on practice/add_digits/addDigits.php
> +    return $res;
убрал

2021-12-28 04:01 UTC, Ifkeybirf commented on practice/add_digits/addDigits.php
> +        return $res;
да, я прогнал. он на одном уровне с свитчем. поправил.

2021-12-28 04:52 UTC, merged