ex#6 isPerfect fuction realization
Ifkeybirf/php-cource-hexlet pull request #9
Opened 2022-01-06 12:22 UTC by Ifkeybirf

exercise #6: function for checking is number is perfect or not

2022-01-10 04:47 UTC, ova777 requested changes

2022-01-10 04:47 UTC, ova777 commented on practice/isPerfect/isPerfect.php
> +        if ($a % $i == 0) {
Лучше делать строгое сравнение

2022-01-10 04:47 UTC, ova777 commented on practice/isPerfect/isPerfect.php
> +    return $dividers == $a;
Лучше делать строгое сравнение

2022-01-10 04:47 UTC, ova777 commented on practice/isPerfect/isPerfect.php
> +function isPerfect(int $a): bool
Решение отличное, но есть недоработка, для $a = 0 будет результат true, хотя 0 не является совершенным числом.

2022-01-11 09:21 UTC, Ifkeybirf commented on practice/isPerfect/isPerfect.php
> +function isPerfect(int $a): bool
damn. I thought it is checked in cycle. strong checking has been added.

2022-01-11 10:13 UTC, ova777 approved these changes
Теперь всё отлично!

2022-01-11 10:32 UTC, merged